// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_WZ7Q8bTcLfjUJBzApEGFvaC_omiUOU',
    appId: '1:982993054371:web:ceb06f747c9adf24baad16',
    messagingSenderId: '982993054371',
    projectId: 'sweetncolours-5cfc2',
    authDomain: 'sweetncolours-5cfc2.firebaseapp.com',
    storageBucket: 'sweetncolours-5cfc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhazHCszpKdgVqy1Q52w5DW_Smz8UZl8',
    appId: '1:982993054371:android:503fea8f253e91c0baad16',
    messagingSenderId: '982993054371',
    projectId: 'sweetncolours-5cfc2',
    storageBucket: 'sweetncolours-5cfc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0CyYJW6iTXr03qOhrS1s8IyQJ18bC4IA',
    appId: '1:982993054371:ios:035b762b21caeb2fbaad16',
    messagingSenderId: '982993054371',
    projectId: 'sweetncolours-5cfc2',
    storageBucket: 'sweetncolours-5cfc2.appspot.com',
    iosClientId: '982993054371-dtdd6rvg592mgg3vkipcidd9lokgobef.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweetncolours',
  );
}
